module.exports = {
    RT_NO_STORE: "지원하지 않는 매장입니다. 다시 시도해주세요.",
    RT_GETWAITING_1: "대기인원은 ",
    RT_GETWAITING_2: "명 입니다.",
    RT_POSTWAITING_1: "대기 신청이 완료되었습니다. 총 대기인원은 ",
    RT_POSTWAITING_2: "명 입니다.",
    RT_GETSTORES_1: "대기 가능한 매장은 ",
    RT_GETSTORES_2: "등이 있습니다.",
    RT_NO_STORE: "어떤 매장을 말씀하시는건가요?",
    RT_GETORDER_1: "고객님의 대기 순서는 ",
    RT_GETORDER_2: "번째이며, 총 ",
    RT_GETORDER_3: "명이 대기하고 있습니다.",
    RT_DUPLICATED: "이미 대기하셔서 대기표 발급하실 수 없습니다.",
    RT_START: "고대기 익스텐션을 시작합니다.",
    RT_GUIDE: "대기 가능한 매장 알려줘, 스타벅스 대기상태 알려줘, 스타벅스 대기표 뽑아줘, 라고 시도해보세요.",
    RT_END: "고대기를 종료합니다.",
    STORES: ["스타벅스", "애슐리", "맥도날드", "버거킹", "피자몰"],
}